# Generated by Django 3.0.2 on 2020-01-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='urls',
            new_name='url',
        ),
    ]
